version: '3.7'
services:
  verifier: # This is also the hostname of the container within the Docker network (i.e. https://opensearch-node1/)
    image: stefno83/tesi-smurino/verifier:1.0.0 # Specifying the latest available image - modify if you want a specific version
    container_name: verifier
    environment:
      - nothing=verifier
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    ports:
      - 8082:8080 # REST API
    expose:
      - "8082"
    networks:
      - rvelastic-net
  producer: # This is also the hostname of the container within the Docker network (i.e. https://opensearch-node1/)
    image: stefno83/tesi-smurino/producer:1.0.0 # Specifying the latest available image - modify if you want a specific version
    container_name: producer
    environment:
      - CUSTOM_KAFKA_ADDRESS=kafka:9092
      - CUSTOM_KAFKA_DESTINATION_TOPIC=develop-1
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    ports:
      - 8083:8080 # REST API
    expose:
      - "8083"
    networks:
      - rvelastic-net

  worker: # This is also the hostname of the container within the Docker network (i.e. https://opensearch-node1/)
    image: stefno83/tesi-smurino/worker:1.0.0 # Specifying the latest available image - modify if you want a specific version
    container_name: worker
    environment:
      - CUSTOM_KAFKA_ADDRESS=kafka:9092
      - CUSTOM_KAFKA_GROUP=my-cg
      - CUSTOM_KAFKA_DESTINATION_TOPIC=develop-2
      - CUSTOM_KAFKA_SOURCE_TOPIC=develop-1
      - CUSTOM_VERIFIER_FIELD=actionEnabled
      - CUSTOM_VERIFIER_ADDRESS=http://verifier:8080/verify
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    ports:
      - 8080:8080 # REST API
    expose:
      - "8080"
    networks:
      - rvelastic-net

  writer: # This is also the hostname of the container within the Docker network (i.e. https://opensearch-node1/)
    image: stefno83/tesi-smurino/writer:1.0.0 # Specifying the latest available image - modify if you want a specific version
    container_name: writer
    restart: on-failure
    environment:
      - CUSTOM_KAFKA_ADDRESS=kafka:9092
      - CUSTOM_KAFKA_SOURCE_TOPIC=develop-2
      - CUSTOM_KAFKA_GROUP=writer-gr-a
      - CUSTOM_OPENSEARCH_ADDRESS=opensearch-node1
      - CUSTOM_OPENSEARCH_PORT=9200
      - CUSTOM_OPENSEARCH_INDEX=rvelastic.index
      - CUSTOM_OPENSEARCH_USER=admin
      - CUSTOM_OPENSEARCH_PASSWORD=admin
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    ports:
      - 8081:8080 # REST API
    expose:
      - "8081"
    networks:
      - rvelastic-net
  #  depends_on:
  #    - opensearch-node1
  #  healthcheck:
  #    test: curl --fail http://localhost:5000/ || exit 1
  #    interval: 40s
  #    timeout: 30s
  #    retries: 3
  #    start_period: 60s

volumes:
  kafka-volume:
  zookeeper-volume:
  opensearch-data1:

networks:
  rvelastic-net: