server:
  port: 8080
spring:
  application:
    name: producer
  kafka:
    consumer:
      auto-offset-reset: earliest

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
  endpoint:
    health:
      enabled: true

custom:
  kafka:
    address: "localhost:9093"
    destination:
      topic: "develop-1"
